language: node_js
node_js: node
env:
  - NODE_ENV=test
# services:
#   - [DATABASE-TYPE]  
# deploy:
#   provider: heroku
#   api_key:
#     secure: [YOUR-API-KEY]
#   app: [YOUR-APP-NAME]
#   on:
#     repo: [YOUR-APP-REPO]